export const departments = [
  "African Studies",
  "Anthropology",
  "Arabic",
  "Bio-Chemistry",
  "Bio-Physics",
  "Botany",
  "Buddhist Studies",
  "Chemistry",
  "Commerce",
  "Computer Science",
  "East Asian Studies",
  "Economics",
  "Education",
  "Electronic Science",
  "English",
  "Environmental Studies",
  "Financial Studies",
  "Genetics",
  "Geography",
  "Geology",
  "Germanic and Romance Studies",
  "Hindi",
  "History",
  "Home Science",
  "Institute of Informatics and Communication",
  "Law",
  "Library and Information Science",
  "Linguistics",
  "Management Studies",
  "Mathematics",
  "Microbiology",
  "Modern Indian Languages and Literary Studies",
  "Music",
  "Operational Research",
  "Persian",
  "Philosophy",
  "Physics and Astrophysics",
  "Plant Molecular Biology",
  "Political Science",
  "Psychology",
  "Punjabi",
  "Sanskrit",
  "Slavonic and Finno-Ugrian Studies",
  "Sociology",
  "Social Work",
  "Statistics",
  "Urdu",
  "Zoology",
];
export const departmentOptions = departments.map((department) => ({
  value: department,
  label: department,
}));
